Feature/Auth
VVMig/social-newtwork pull request #14
Opened 2021-04-02 10:47 UTC by VVMig

2021-04-05 11:50 UTC, EgorPashko requested changes

2021-04-05 11:50 UTC, EgorPashko commented on src/app/auth/Auth.tsx
> +  const [signIn, setSignIn] = useState<boolean>(true);
```<boolean>``` можно опустить

2021-04-05 11:50 UTC, EgorPashko commented on src/app/auth/Form.tsx
> +const shema = yup.object().shape({
вынеси в отдельный файл validationSchema

2021-04-05 11:50 UTC, EgorPashko commented on src/app/auth/Form.tsx
> +        initialValues={{
initialValues создай объект и положи рядом с валидационной схемой

2021-04-05 11:50 UTC, EgorPashko commented on src/app/auth/LeftText.tsx
> +export const LeftText = ({ signIn }: WelcomeProps) => {
app/auth/leftText не понятно что за левый текст. Лучше SignInText/SignOutText

2021-04-05 11:50 UTC, EgorPashko commented on src/app/auth/SignUpInputs.tsx
> +      <InputGroup
Дублирование кода.
Создай конфиг 
fields = {
name: keyof твой интерфейс,
placeholder: ...,
iconType: IconType.User
}

2021-04-05 11:50 UTC, EgorPashko commented on src/app/auth/animations.ts
> +0%{
Настрой приттиер чтобы он форматировал

2021-04-06 12:33 UTC, EgorPashko requested changes

2021-04-06 12:33 UTC, EgorPashko commented on src/app/auth/Auth.tsx
> +  const [signin, setSignin] = useState(true);
signin -> signIn

2021-04-06 12:33 UTC, EgorPashko commented on src/app/auth/Form.tsx
> +          console.log(values);
?

2021-04-06 12:33 UTC, EgorPashko commented on src/app/auth/Form.tsx
> +              <FormInputs fields={signUpFields} />
дублирование

2021-04-06 12:33 UTC, EgorPashko commented on src/app/auth/SignUpText.tsx
> +    <Styled.SignUpText signin={signin}>
signin -> signIn Везде

2021-04-06 12:41 UTC, VVMig commented on src/app/auth/Form.tsx
> +          console.log(values);
У меня такого нет в последнем коммите

2021-04-06 12:42 UTC, VVMig commented on src/app/auth/Form.tsx
> +              <FormInputs fields={signUpFields} />
И такого нет)

2021-04-06 15:06 UTC, merged