Feature/private routes
VVMig/social-newtwork pull request #18
Opened 2021-04-12 14:42 UTC by VVMig

2021-04-13 10:58 UTC, EgorPashko requested changes

2021-04-13 10:58 UTC, EgorPashko commented on src/app/App.tsx
> +          <Route path="/authorization">
Перемести в константу

2021-04-13 10:58 UTC, EgorPashko commented on src/app/App.tsx
>      <BrowserRouter>
store.user.authorizeUser(); -> используй afterCreate

2021-04-13 10:58 UTC, EgorPashko commented on src/app/routes/PrivateRoute.tsx
> +  ...rest
rest -> props

2021-04-13 10:58 UTC, EgorPashko commented on src/app/routes/RedirectRoute.tsx
> +export const RedirectRoute: React.FC<RouteProps> = ({ children, ...rest }) => {
rest -> props

2021-04-14 13:23 UTC, VVMig commented on src/app/App.tsx
>    }, []);
Сделал так, а не через afterCreate, так как нужно было хендлить лоадинг. Консоль лог забыл убрать

2021-05-04 16:29 UTC, closed without merging