add styled-components
VVMig/social-newtwork pull request #4
Opened 2021-03-23 12:25 UTC by VVMig

2021-03-24 08:47 UTC, EgorPashko requested changes

2021-03-24 08:47 UTC, EgorPashko commented on src/packages/components/header/Styled.tsx
> +`;
Это касается всех файлов styled.ts
и нужно переименовать Styled -> styled

2021-03-24 08:47 UTC, EgorPashko commented on src/packages/components/sidebar-widget/Styled.tsx
> +    width: 0;
Притер должен выровнять это. Исправь

2021-03-24 08:47 UTC, EgorPashko commented on src/packages/components/sidebar-widget/Styled.tsx
> +  &:last-child {
Удали из проекта last-child. Так как это может привести к багам

2021-03-24 08:47 UTC, EgorPashko commented on src/packages/components/sidebar-widget/Styled.tsx
> +  padding: 0 0 0 15px;
padding-left

2021-03-24 08:47 UTC, EgorPashko commented on src/packages/components/sidebar-widget/WidgetItem.tsx
> +import { Img, Info, Item, Name, Online, Status } from './Styled';
import { Styled } from './styled'

2021-03-24 08:47 UTC, EgorPashko commented on src/packages/components/sidebar/Logo.tsx
> +import { Div } from './Styled';
Плохое название

2021-03-24 08:47 UTC, EgorPashko commented on src/packages/components/sidebar/Logo.tsx
> +      <Div></Div>
<Div />

2021-03-26 07:00 UTC, EgorPashko requested changes

2021-03-26 07:00 UTC, EgorPashko commented on src/packages/components/header/Navbar.tsx
> +        <Styled.StyledLink to={x.route} key={i} title={x.title}>
Styled.StyledLink -> Styled.Link

2021-03-26 07:00 UTC, EgorPashko commented on src/packages/components/header/PageIcon.tsx
>  export const PageIcon: React.FC = ({ children }) => {
Это находится в components/header. О какой Page идет речь ? Может лучше переименовать ?

2021-03-26 07:00 UTC, EgorPashko commented on src/packages/components/sidebar/styled.ts
> +  &::-webkit-scrollbar {
Подскажи зачем тебе тут ```-webkit```

2021-03-26 07:00 UTC, EgorPashko commented on src/packages/components/sidebar/styled.ts
> +  z-index: 2;
Создай константу в ``` components/zIndex -> zIndex ={ sideBarMenu: 1, sideButPopover: 25} ....```

2021-03-26 07:00 UTC, EgorPashko commented on src/packages/components/underline/interfaces.ts
> +export interface Props {
не стоит создавать отдельный файл только ради 1 интерфейса с 1 полем

2021-03-26 09:29 UTC, VVMig commented on src/packages/components/sidebar/styled.ts
> +  &::-webkit-scrollbar {
Так как у него есть свойста, которые могу стилизовать scrollbar

2021-03-30 08:17 UTC, merged